export const initialState = {
  alias: 'Waivio Service',
  history: {
    action: 'POP',
    block: 'func',
    createHref: 'func',
    go: 'func',
    goBack: 'func',
    goForward: 'func',
    length: 50,
    listen: 'func',
    location: {
      hash: '',
      key: 'xq6l95',
      pathname: '/rewards/payables',
      search: '',
      state: null,
    },
  },
  location: {
    hash: '',
    key: 'xq6l95',
    pathname: '/rewards/payables',
    search: '',
    state: null,
  },
  match: {
    isExact: true,
    params: {},
    path: '/rewards/payables',
    url: '/rewards/payables',
  },
  name: 'wiv01',
  path: '/rewards/payables/@wiv01',
  payable: 0.01,
  staticContext: undefined,
};

export const stateForMemo = {
  alias: 'Waivio Service',
  history: {
    action: 'POP',
    block: 'func',
    createHref: 'func',
    go: 'func',
    goBack: 'func',
    goForward: 'func',
    length: 50,
    listen: 'func',
    location: {
      hash: '',
      key: 'xq6l95',
      pathname: '/rewards/payables',
      search: '',
      state: null,
    },
    push: 'func',
    replace: 'func',
  },
  location: {
    hash: '',
    key: 'xq6l95',
    pathname: '/rewards/payables',
    search: '',
    state: null,
  },
  match: {
    isExact: true,
    params: {},
    path: '/rewards/payables',
    url: '/rewards/payables',
  },
  name: 'waivio_',
  path: '/rewards/payables/@wiv01',
  payable: 0.01,
  staticContext: undefined,
};

export const stateForChangeMatchPath = {
  alias: 'Waivio Service',
  history: {
    action: 'POP',
    block: 'func',
    createHref: 'func',
    go: 'func',
    goBack: 'func',
    goForward: 'func',
    length: 50,
    listen: 'func',
    location: {
      hash: '',
      key: 'xq6l95',
      pathname: '/rewards/receivables',
      search: '',
      state: null,
    },
    push: 'func',
    replace: 'func',
  },
  location: {
    hash: '',
    key: 'xq6l95',
    pathname: '/rewards/receivables',
    search: '',
    state: null,
  },
  match: {
    isExact: true,
    params: {},
    path: '/rewards/receivables',
    url: '/rewards/receivables',
  },
  name: 'waivio_',
  path: '/rewards/receivables/',
  payable: 0.01,
  staticContext: undefined,
};
